### ISSUE TITLE
Version 5.6.0 dependencies Error

### ISSUE THREAD

**Issue by yinglovezhuzhu** [line/line-sdk-android#106]
I use version 5.6.0 in my gradle build，but I got an build error like below. 

`
Could not determine the dependencies of task ':rsdk_line:compileDebugAidl'.
> Could not resolve all task dependencies for configuration ':rsdk_line:debugCompileClasspath'.
   > Could not find :unspecified:.
     Required by:
         project :rsdk_line > com.linecorp.linesdk:linesdk:5.6.0

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
`

and I found the pom.xml file contains a dependencies like below, can you fix it?
`
<dependency>
      <groupId/>
      <artifactId>unspecified</artifactId>
      <version/>
    </dependency>
`

**Comment by plateaukao** [comment]
Hi, @yinglovezhuzhu 
Please follow issue template to provide necessary information so that we can help to investigate your issue. Also, if possible, please provide a sample that can reproduce your issue. You only said you use version 5.6.0, but we don't know how you use it in your project, and what other tools you use for your project.

Suggesting you that you try to build the attached sample app in this git to make sure it run okay on your environment. If so, you can refer to how it's being used.

**Comment by plateaukao** [comment]
close due to no further information provided.
