### ISSUE TITLE
AccessToken is no longer available If the app is updated to targetSdkVersion 28

### ISSUE THREAD

**Issue by hseung** [line/line-sdk-android#27]
## Is it a security issue?
No

## What did you do?
1. Build and run the sample app as it is (targetSdkVersion 26)
2. Log in with LINE
3. Click [APIs] button to navigate to ApisFragment
4. Click [getCurrentToken] and check that access token is available in the generated log.
5. Build the app again with targetSdkVersion 28
6. Click [APIs] button to navigate to ApisFragment again.
7. Click [getCurrentToken]

## What did you expect?

Access token should be available as before.

## What happened actually?

Got INTERNAL_ERROR log with message of "The cached access token does not exist'

## Your environment?

LINE sdk 5.1, Android Studio 3.5, Android Pie, SM-G950N

## Sample project

You can reproduce the issue just by changing targetSdkVersion to 28

------------------

As you may already know, Google Play requires all apps to target api 28 from November 2019. (https://developer.android.com/distribute/best-practices/develop/target-sdk)
So I would need your immediate attention to this issue to keep maintaining my app in Google Play even after the new policy is applied on Nov.

**Comment by LiYing2010** [comment]
@hseung :
Thank you very much for reporting this,
I will check it

**Comment by LiYing2010** [comment]
@plateaukao  san:

Sorry,
I can't reproduce this on my virtual device (Android 9.0)
and unfortunately, I can't find a real device (Android 9.0) for now.

Could you please check this?

**Comment by plateaukao** [comment]
Hello, @hseung 

Thanks for your report. After investigation, we found that Google has some behavior changes to Android 9 (API level 28). And one of it impacts the way of line-sdk encrypt/decrypt the token data we stored locally. Specifically speaking, the result of using `Build.SERIAL` is changed.

**Google's doc**
https://developer.android.com/about/versions/pie/android-9.0-changes-28#privacy-changes-p
it says that 

> If your app targets Android 9, you should keep the following behavior changes in mind. These updates to device serial and DNS information enhance user privacy.
> Build serial number deprecation
> 
> In Android 9, Build.SERIAL is always set to "UNKNOWN" to protect users' privacy.
> 
> If your app needs to access a device's hardware serial number, you should instead request the READ_PHONE_STATE permission, then call getSerial().

**line-sdk decryption/encryption key generation**
https://git.linecorp.com/LINE-Client/line-android-security/blob/14b0b934ee56638d18f65e2c2e7e97cd75a6beb1/src/com/linecorp/android/security/encryption/StringCipher.java#L232

Because the key generated is changed after changing targetSDK version to 28 and above, it's no longer possible to retrieve the stored token in shared preferences.

Although it's still possible to get the same serial value after targetSDK version 28, it needs the app to have granted the permission of `READ_PHONE_STATE`, which may raise users' doubts why this permission is necessary.

Our suggestion is that when encountering this error, please ask users to login again, so the new token will be generated and saved in shared preference with new generated key. 

If you have any suggestions, please let us know. We would love to have a more graceful migration for this change.

**Comment by hseung** [comment]
Thanks for the confirmation @plateaukao 

Actually it's quite frustrating situation but I do understand your explanation about the root of cause as I'm also aware of the behavior changes in P.

I also do not have any idea for the graceful migration but would be really grateful if you or other guys can come up with a good solution.

And there's one more thing I would like to ask you about side effect of the issue.
When users encounter this error and log in again, I wonder if the result of `LineApiResponse#getProfile` would be the same data as before or not, especially `LineProfile#userID`. I'm worried about this case because the actual access token will get changed after the app migration and all request to your server seems to contain the access token for user identification.

**Comment by LiYing2010** [comment]
> When users encounter this error and log in again, I wonder if the result of `LineApiResponse#getProfile` would be the same data as before or not, especially `LineProfile#userID`. I'm worried about this case because the actual access token will get changed after the app migration and all request to your server seems to contain the access token for user identification.


Don't worry, this part will not change when user login again.
`access token` will change, but `user profile` will be all the same, no matter how many times user log in
