### ISSUE TITLE
Help needed: integrating with Capacitor's OAuth2 plugin

### ISSUE THREAD

**Issue by leshik** [line/line-sdk-android#5]
Hello,

[Capacitor](https://capacitor.ionicframework.com) is a new PWA framework that is also going to be integrated into the well known Ionic Framework, which is now based on Cordova (that said, Capacitor will eventually replace Cordova).

I need some suggestions on how the Line Login API could be integrated into Capacitor's [OAuth2 plugin](https://github.com/moberwasserlechner/capacitor-oauth2). At first, I thought it might look similar to Facebook, but seems Line SDK for Android lacks ready-to-use login activity and callbacks that can be used. I was able to integrate it on iOS, but now struggle with Android. Some examples would be really helpful.

PS: Cordova suggestions would also be helpful as long as they could be adapted to Capacitor, some plugins already exist, but they are based on old SDK versions.

**Comment by leshik** [comment]
@plateaukao @perthcpe23 @LiYing2010 can anybody help? :)

**Comment by plateaukao** [comment]
Hello, @leshik 

Since LINE SDK's login process is not 100% compatible with OAuth2 standard, I am afraid that you can't use OAuth2 plugin directly with LINE SDK.

You can check LINE SDK documentation here: https://developers.line.biz/en/docs/android-sdk/integrate-line-login/  , login activity is provided by calling `LineLoginApi.getLoginIntent()` and pass it to `startActivityForResult()`. And then, you can deal with results in `onActivityResult()`.

Hope this information helps.

**Comment by plateaukao** [comment]
Close now for having no comments for a while.
