### ISSUE TITLE
LineApiError{httpResponseCode=200, message='java.io.IOException: org.json.JSONException: Unable to load class named [io.jsonwebtoken.io.JacksonDeserializer]

### ISSUE THREAD

**Issue by KeunWoongYuk** [line/line-sdk-android#68]
## What did you do?

> 3rd Login

## What did you expect?

> get user email information

## What happened actually?

> Login FAILED!
 E/ERROR: LineApiError{httpResponseCode=200, message='java.io.IOException: org.json.JSONException: Unable to load class named [io.jsonwebtoken.io.JacksonDeserializer] from the thread context, current, or system/application ClassLoaders.  All heuristics have been exhausted.  Class could not be found.

## Your environment?

> implementation 'com.linecorp.linesdk:linesdk:5.4.1'

**Comment by LiYing2010** [comment]
looks like you hit some class dependency issue.
could you please share us your `build.gradle` file?

I guess you introduced `jackson` in your project, or by some other dependency in your project,
if that's true, you can reference this about workaround:
https://github.com/jwtk/jjwt/issues/397
if this workaround works for you, please tell us

I think this issue is fixed in `io.jsonwebtoken:jjwt` v0.10.6,
we will upgrade our `io.jsonwebtoken:jjwt` dependency  to the latest version later

**Comment by LiYing2010** [comment]
We have upgraded `jjwt` to the latest version `0.11.1` : #72 
It will be released with next version of `line-sdk-android`
I think this will fix this issue.

**Comment by plateaukao** [comment]
Close due to no response for over 2 months.
